name: hazard-map
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # Core
  - numpy
  - pandas

  # Viz
  - matplotlib
  - altair

  # Geospatial stack (GeoPandas + drivers)
  - geopandas
  - fiona
  - gdal
  - pyproj
  - shapely
  - rtree

  # For reading GeoPackage
  - sqlite
  - libspatialite

  # Streamlit itself (conda)
  - streamlit

  # pip-only packages
  - pip:
      - folium
      - branca
      - streamlit-folium
